"""生成 exe 的版本资源（Windows 文件属性 → 详细信息）。

用法（一般由打包脚本调用，不手工执行）::

    python tools/version_info.py build/version_info.txt

为什么要它：没有版本资源的 exe 在"文件属性 → 详细信息"里是空白，
"应用和功能"里也只能靠安装包记录的版本号，排查"用户装的是哪一版"很费劲。
版本号从 :data:`app.APP_VERSION` 取，保证与界面、安装包、自检报告同源。
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app import APP_NAME, APP_NAME_EN, APP_VERSION  # noqa: E402

LEGAL_COPYRIGHT = "Copyright (c) 2026 collinszheng. MIT License."
#: 0x0409 = 英语（美国），1200 = Unicode；两者合起来是 StringTable 的语言标识
LANG_ID = "040904B0"
TRANSLATION = (0x0409, 1200)


def version_tuple(version: str) -> tuple[int, int, int, int]:
    """``"1.0.1"`` → ``(1, 0, 1, 0)``。

    Windows 的版本资源只认四段数字，因此预发布后缀直接忽略
    （``"1.0.0-beta1"`` → ``(1, 0, 0, 0)``，而不是把 ``beta1`` 的数字当成第四段）。
    """
    core = re.split(r"[^0-9.]", version, maxsplit=1)[0]
    parts = [int(chunk) for chunk in core.split(".") if chunk.isdigit()]
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])  # type: ignore[return-value]


def build_text(version: str = APP_VERSION) -> str:
    """返回 PyInstaller 能直接 eval 的 VSVersionInfo 文本。"""
    numbers = version_tuple(version)
    version_text = ".".join(str(value) for value in numbers)
    strings = (
        ("CompanyName", APP_NAME),
        ("FileDescription", APP_NAME),
        ("FileVersion", version_text),
        ("InternalName", APP_NAME_EN),
        ("LegalCopyright", LEGAL_COPYRIGHT),
        ("OriginalFilename", f"{APP_NAME_EN}.exe"),
        ("ProductName", APP_NAME),
        ("ProductVersion", version_text),
    )
    entries = ",\n".join(
        f"                StringStruct({key!r}, {value!r})" for key, value in strings
    )
    return (
        "# Generated by tools/version_info.py - do not edit by hand.\n"
        "# Version comes from app.APP_VERSION (kept ASCII so the build never depends on\n"
        "# the console/file encoding when PyInstaller reads this file).\n"
        "VSVersionInfo(\n"
        f"  ffi=FixedFileInfo(filevers={numbers}, prodvers={numbers},\n"
        "                  mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0,\n"
        "                  date=(0, 0)),\n"
        "  kids=[StringFileInfo([\n"
        f"      StringTable({LANG_ID!r}, [\n"
        f"{entries}\n"
        "      ])]),\n"
        f"      VarFileInfo([VarStruct('Translation', [{TRANSLATION[0]}, {TRANSLATION[1]}])])]\n"
        ")\n"
    )


def write(target: Path, version: str = APP_VERSION) -> Path:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(build_text(version), encoding="utf-8")
    return target


def main(argv: list[str] | None = None) -> int:
    arguments = (argv if argv is not None else sys.argv[1:]) or ["build/version_info.txt"]
    target = Path(arguments[0]).resolve()
    write(target)
    print(f"版本资源已生成：{target}（{APP_NAME} {APP_VERSION}）")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
